/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pokemon/v1/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        PokeapiLanguageCodes: "ja-Hrkt" | "ja" | "ko" | "fr" | "de" | "en" | "es";
        Type: {
            /** @description Path to the URL which will point at sprites.pokecompanion.com */
            icon: string;
            /** @description The Pokeapi name for this type */
            name: string;
        };
        /** @enum {string} */
        PokeapiVersionGroups: "home" | "red-blue" | "yellow" | "gold-silver" | "crystal" | "ruby-sapphire" | "emerald" | "firered-leafgreen" | "diamond-pearl" | "platinum" | "heartgold-soulsilver" | "black-white" | "black-2-white-2" | "x-y" | "omega-ruby-alpha-sapphire" | "sun-moon" | "ultra-sun-ultra-moon" | "lets-go-pikachu-lets-go-eevee" | "sword-shield" | "brilliant-diamond-and-shining-pearl" | "legends-arceus" | "scarlet-violet" | "legends-za";
        PokeapiNamedApiResource: {
            /** @description https://pokeapi.co/api/v2/.../entry/id/ */
            url: string;
            /** @description Short name */
            name: string;
        };
        PokemonV1Response: {
            varieties: {
                pokecompanionUrl: string;
                isDefault: boolean;
                displayName: string;
                name: string;
            }[];
            abilities: {
                /** Format: double */
                slot: number;
                is_hidden: boolean;
                ability: components["schemas"]["PokeapiNamedApiResource"];
            }[];
            presenceInGame: {
                /** @enum {number|null} */
                pokedexNumber: null;
                /** @enum {boolean} */
                present: false;
                /**
                 * @description Playback of the game that was used in the request - mostly for clarity
                 * @example scarlet-violet
                 */
                game: components["schemas"]["PokeapiVersionGroups"];
            } | {
                /** Format: double */
                pokedexNumber: number;
                /** @enum {boolean} */
                present: true;
                /**
                 * @description Playback of the game that was used in the request - mostly for clarity
                 * @example scarlet-violet
                 */
                game: components["schemas"]["PokeapiVersionGroups"];
            };
            evolutionChain: {
                /** @description Indicates wheather both source + target evolutions are present in the current game.
                 *     An imperfect measure since it is based on the national dex ID and does not take variants
                 *     or gender into account
                 *     Some Pokemon, as well as having an evolution at all, are also region locked so they can only
                 *     evolve in that specific region. https://github.com/PokeAPI/pokeapi/issues/1315 */
                isValidInGame: boolean;
                target: {
                    /**
                     * @description The URL that should be navigated to when this Pokemon is clicked
                     * @example /pokemon/4
                     */
                    pokemonUrl: string;
                    /**
                     * @description URL for the sprite of this Pokemon
                     * @example https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png
                     */
                    spriteUrl: string;
                };
                /** @description Additional requirements that will only be */
                requirements: {
                    supplementary?: string;
                    info: string | number;
                    /** @enum {string} */
                    type: "hold-item" | "friendship" | "shed" | "three-critical-hits" | "beauty" | "rain" | "daytime" | "trade_for" | "party_have" | "other" | "stats" | "know_move" | "know_move_type" | "affection" | "location" | "level-up" | "use-item" | "recoil-damage" | "battle-leader" | "game-specific" | "no-animation" | "multiplayer" | "use-move" | "gender" | "party_type" | "collect_items";
                }[];
                /**
                 * @description Description of what will trigger the evolution
                 * @example Level 24
                 */
                trigger: string;
                source: {
                    /**
                     * @description The URL that should be navigated to when this Pokemon is clicked
                     * @example /pokemon/4
                     */
                    pokemonUrl: string;
                    /**
                     * @description URL for the sprite of this Pokemon
                     * @example https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png
                     */
                    spriteUrl: string;
                };
            }[];
            types: {
                weakAgainst: (components["schemas"]["Type"] & {
                    /** Format: double */
                    multiplier: number;
                })[];
                resists: (components["schemas"]["Type"] & {
                    /** Format: double */
                    multiplier: number;
                })[];
                own: components["schemas"]["Type"][];
            };
            sprites: {
                isBack: boolean;
                hasFemale: boolean;
                hasShiny: boolean;
                alt: string;
                url: string;
            }[];
            /**
             * @description Path to a .ogg file with this pokemon's cry
             * @example https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/3.ogg
             */
            cry: string;
            /**
             * Format: double
             * @description Weight in grams
             * @example 3500
             */
            weight: number;
            /**
             * Format: double
             * @description Height in cm
             * @example 176
             */
            height: number;
            pokedexEntries: {
                textEntry: string;
                /** @description A display friendly game name, NOT the pokeapi name */
                game: string;
                language: components["schemas"]["PokeapiLanguageCodes"];
            }[];
            name: string;
            /** Format: double */
            id: number;
            __internal: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonV1Response"];
                };
            };
        };
    };
}
