/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pokemon/v1/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPokemon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        PokeapiLanguageCodes: "ja-Hrkt" | "ja" | "ko" | "fr" | "de" | "en" | "es";
        Type: {
            /** @description Path to the URL which will point at sprites.pokecompanion.com */
            icon: string;
            /** @description The Pokeapi name for this type */
            name: string;
        };
        PokemonMove: {
            /** Format: double */
            id: number;
            names: {
                name: string;
                language: {
                    url: string;
                    name: string;
                };
            }[];
            type: {
                url: string;
                name: string;
            };
            damage_class: {
                url: string;
                name: string;
            };
            /** Format: double */
            level?: number;
        };
        /** @enum {string} */
        PokeapiStatType: "hp" | "attack" | "defense" | "speed" | "special-attack" | "special-defense";
        PokemonV1Response: {
            pokemon: {
                /** Format: double */
                weight: number;
                /** Format: double */
                height: number;
                stats: {
                    url: string;
                    name: components["schemas"]["PokeapiStatType"];
                }[];
                forms: {
                    url: string;
                    name: string;
                }[];
                /** Format: double */
                base_experience: number;
                moves: {
                    [key: string]: {
                        tutorMoves: components["schemas"]["PokemonMove"][];
                        breedMoves: components["schemas"]["PokemonMove"][];
                        tmMoves: components["schemas"]["PokemonMove"][];
                        levelupMoves: components["schemas"]["PokemonMove"][];
                    };
                }[];
                varietyForms: {
                    name: string;
                }[];
                types: {
                    url: string;
                    icon: string;
                    name: string;
                }[];
                name: string;
                abilities: {
                    ability: {
                        url: string;
                        name: string;
                    };
                    /** Format: double */
                    slot: number;
                    is_hidden: boolean;
                }[];
            };
            evolutionChain: {
                target: {
                    /**
                     * @description The URL that should be navigated to when this Pokemon is clicked
                     * @example /pokemon/4
                     */
                    pokemonUrl: string;
                    /**
                     * @description URL for the sprite of this Pokemon
                     * @example https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png
                     */
                    spriteUrl: string;
                };
                /** @description Additional requirements that will only be */
                requirements: {
                    supplementary?: string;
                    info: string | number;
                    /** @enum {string} */
                    type: "hold-item" | "friendship" | "shed" | "three-critical-hits" | "beauty" | "rain" | "daytime" | "trade_for" | "party_have" | "other" | "stats" | "know_move" | "know_move_type" | "affection" | "location" | "level-up" | "use-item" | "recoil-damage" | "battle-leader" | "game-specific" | "no-animation" | "multiplayer" | "use-move" | "gender" | "party_type" | "collect_items";
                }[];
                /**
                 * @description Description of what will trigger the evolution
                 * @example Level 24
                 */
                trigger: string;
                source: {
                    /**
                     * @description The URL that should be navigated to when this Pokemon is clicked
                     * @example /pokemon/4
                     */
                    pokemonUrl: string;
                    /**
                     * @description URL for the sprite of this Pokemon
                     * @example https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png
                     */
                    spriteUrl: string;
                };
            }[];
            types: {
                weakAgainst: (components["schemas"]["Type"] & {
                    /** Format: double */
                    multiplier: number;
                })[];
                resists: (components["schemas"]["Type"] & {
                    /** Format: double */
                    multiplier: number;
                })[];
                own: components["schemas"]["Type"][];
            };
            sprites: {
                isPerfectMatch: boolean;
                matchesForm: boolean;
                isBack: boolean;
                matchesVariety: boolean;
                hasFemale: boolean;
                hasShiny: boolean;
                alt: string;
                url: string;
            }[];
            /**
             * @description Path to a .ogg file with this pokemon's cry
             * @example https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/3.ogg
             */
            cry: string;
            /**
             * Format: double
             * @description Weight in grams
             * @example 3500
             */
            weight: number;
            /**
             * Format: double
             * @description Height in cm
             * @example 176
             */
            height: number;
            pokedexEntries: {
                textEntry: string;
                /** @description A display friendly game name, NOT the pokeapi name */
                game: string;
                language: components["schemas"]["PokeapiLanguageCodes"];
            }[];
            /** Format: double */
            id: number;
            __internal: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetPokemon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonV1Response"];
                };
            };
        };
    };
}
